[package]
name = "integration-tests"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "test-locator"
path = "locator.rs"

[[test]]
name = "di_diun-tests"
path = "tests/di_diun.rs"

[[test]]
name = "to-tests"
path = "tests/to.rs"

[dependencies]
anyhow = "1"
tempfile = "3"
tera = "1"
lazy_static = "1.4.0"
openssl = "0.10"
libc = "0.2"
reqwest = "0.11"
tokio = "1.12.0"
serde_cbor = "0.11"
pretty_assertions = "1.0.0"
paste = "1.0"
serial_test = "1.0.0"

fdo-data-formats = { path = "../data-formats" }
fdo-util = { path = "../util" }
